### ISSUE TITLE
Build fails on NixOS

### ISSUE THREAD

**Issue by jasom** [tomszilagyi/zutty#1] opened 2021-01-12 06:11 UTC
This doesn't look Nix specific, but rather due to the specific GCC version used.

nx and ny are uint16_t which gets upgraded to a signed-integer before arithmetic happens on any target where int is larger than 16 bits.

There are multiple ways to fix this; a cast of either nx or ny to unsigned int is sufficient.  Simply adding something to suppress the warning is reasonable in this specific case as well.

```
../src/font.cc: In member function 'void zutty::Font::load()':
../src/font.cc:88:25: error: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Werror=sign-compare]
   88 |          while (nx * ny < n_glyphs)
      |                 ~~~~~~~~^~~~~~~~~~
```

**Comment by tomszilagyi** [comment] 2021-01-12 07:43
Thank you for reporting this! May I ask what GCC version you use (output of `gcc -v`)?

**Comment by NegentropicMan** [comment] 2021-01-12 19:02
Same problem here (nixos stable).
gcc is 9.3.0

**Comment by tomszilagyi** [comment] 2021-01-12 20:15
Thanks -- interestingly, I do not get any such error with GCC 10.2.1 (20201224), nor with GCC 8.3.0 (2018), nor with GCC 6.3.0 (20170516). Will look into reproducing this (the fix is trivial, I am more interested in understanding why I do not get an error with any of my compilers).

Incidentally, if you go past this error (using any of the posted workarounds), does the rest of the code compile for you?

**Comment by tomszilagyi** [comment] 2021-01-12 20:29
So, I successfully compiled Zutty with Debian's GCC-9 (9.3.0)
I am not familiar with NixOS, is there anything extra going on with its compiler?
Can you do a compile with `./waf -v` and report on the exact compiler args list that you see? (Only for the failing compilation unit is enough.)
Thanks!

**Comment by jasom** [comment] 2021-01-12 20:33
@tomszilagyi 

```

configuring
configure flags: --prefix=/nix/store/03rlzg11avcydbxaffypjy9dda7r1k3z-zutty-c792cf15fba8a6060a85712e5f188cf756d09ad7 configure
Setting top to                           : /build/source 
Setting out to                           : /build/source/build 
Zutty version                            : 0.6 
Debug build                              : no 
Checking for 'g++' (C++ compiler)        : g++ 
Checking for program 'pkg-config'        : /nix/store/131vdr1hvmmk8icrdfppa4ksbg3jdjxr-pkg-config-wrapper-0.29.2/bin/pkg-config 
Checking for 'freetype2'                 : yes 
Checking for 'xmu'                       : yes 
Checking for header EGL/egl.h            : yes 
Checking for header GLES3/gl31.h         : yes 
'configure' finished successfully (0.381s)
building
build flags: -v build
Waf: Entering directory `/build/source/build'
[ 1/12] Compiling src/options.cc
20:32:44 runner ['g++', '-DZUTTY_VERSION="0.6"', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wsign-compare', '-std=c++14', '-g', '-ggdb', '-O2', '-march=native', '-fno-omit-frame-pointer', '-fPIC', '-fsigned-char', '-Werror', '-I/nix/store/pml24684ad5a8a7n10m8s6xkchncxkyd-freetype-2.10.2-dev/include/freetype2', '-I/nix/store/f95lp0api6ib9bqv7r099mip8ia9gxwv-libXmu-1.1.3-dev/include', '-I/nix/store/s2p4r9sd0cib1sp4w9n4yg0gzjahcvs3-libX11-1.6.12-dev/include', '-I/nix/store/4hv04g8figg8gp6aylqp9q64pqy4xsbv-xorgproto-2019.1/include', '-I/nix/store/j3pzr8vam8j46hwlv9f1d6s39hfvsjmc-libXt-1.2.0-dev/include', '-DHAVE_FT=1', '-DHAVE_XMU=1', '-DHAVE_EGL_EGL_H=1', '-DHAVE_GLES3_GL31_H=1', '../src/options.cc', '-c', '-o/build/source/build/src/options.cc.1.o']
[ 2/12] Compiling src/fontpack.cc
20:32:44 runner ['g++', '-DZUTTY_VERSION="0.6"', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wsign-compare', '-std=c++14', '-g', '-ggdb', '-O2', '-march=native', '-fno-omit-frame-pointer', '-fPIC', '-fsigned-char', '-Werror', '-I/nix/store/pml24684ad5a8a7n10m8s6xkchncxkyd-freetype-2.10.2-dev/include/freetype2', '-I/nix/store/f95lp0api6ib9bqv7r099mip8ia9gxwv-libXmu-1.1.3-dev/include', '-I/nix/store/s2p4r9sd0cib1sp4w9n4yg0gzjahcvs3-libX11-1.6.12-dev/include', '-I/nix/store/4hv04g8figg8gp6aylqp9q64pqy4xsbv-xorgproto-2019.1/include', '-I/nix/store/j3pzr8vam8j46hwlv9f1d6s39hfvsjmc-libXt-1.2.0-dev/include', '-DHAVE_FT=1', '-DHAVE_XMU=1', '-DHAVE_EGL_EGL_H=1', '-DHAVE_GLES3_GL31_H=1', '../src/fontpack.cc', '-c', '-o/build/source/build/src/fontpack.cc.1.o']
[ 3/12] Compiling src/charvdev.cc
20:32:44 runner ['g++', '-DZUTTY_VERSION="0.6"', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wsign-compare', '-std=c++14', '-g', '-ggdb', '-O2', '-march=native', '-fno-omit-frame-pointer', '-fPIC', '-fsigned-char', '-Werror', '-I/nix/store/pml24684ad5a8a7n10m8s6xkchncxkyd-freetype-2.10.2-dev/include/freetype2', '-I/nix/store/f95lp0api6ib9bqv7r099mip8ia9gxwv-libXmu-1.1.3-dev/include', '-I/nix/store/s2p4r9sd0cib1sp4w9n4yg0gzjahcvs3-libX11-1.6.12-dev/include', '-I/nix/store/4hv04g8figg8gp6aylqp9q64pqy4xsbv-xorgproto-2019.1/include', '-I/nix/store/j3pzr8vam8j46hwlv9f1d6s39hfvsjmc-libXt-1.2.0-dev/include', '-DHAVE_FT=1', '-DHAVE_XMU=1', '-DHAVE_EGL_EGL_H=1', '-DHAVE_GLES3_GL31_H=1', '../src/charvdev.cc', '-c', '-o/build/source/build/src/charvdev.cc.1.o']
[ 4/12] Compiling src/font.cc
20:32:44 runner ['g++', '-DZUTTY_VERSION="0.6"', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wsign-compare', '-std=c++14', '-g', '-ggdb', '-O2', '-march=native', '-fno-omit-frame-pointer', '-fPIC', '-fsigned-char', '-Werror', '-I/nix/store/pml24684ad5a8a7n10m8s6xkchncxkyd-freetype-2.10.2-dev/include/freetype2', '-I/nix/store/f95lp0api6ib9bqv7r099mip8ia9gxwv-libXmu-1.1.3-dev/include', '-I/nix/store/s2p4r9sd0cib1sp4w9n4yg0gzjahcvs3-libX11-1.6.12-dev/include', '-I/nix/store/4hv04g8figg8gp6aylqp9q64pqy4xsbv-xorgproto-2019.1/include', '-I/nix/store/j3pzr8vam8j46hwlv9f1d6s39hfvsjmc-libXt-1.2.0-dev/include', '-DHAVE_FT=1', '-DHAVE_XMU=1', '-DHAVE_EGL_EGL_H=1', '-DHAVE_GLES3_GL31_H=1', '../src/font.cc', '-c', '-o/build/source/build/src/font.cc.1.o']
[ 5/12] Compiling src/selmgr.cc
20:32:44 runner ['g++', '-DZUTTY_VERSION="0.6"', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wsign-compare', '-std=c++14', '-g', '-ggdb', '-O2', '-march=native', '-fno-omit-frame-pointer', '-fPIC', '-fsigned-char', '-Werror', '-I/nix/store/pml24684ad5a8a7n10m8s6xkchncxkyd-freetype-2.10.2-dev/include/freetype2', '-I/nix/store/f95lp0api6ib9bqv7r099mip8ia9gxwv-libXmu-1.1.3-dev/include', '-I/nix/store/s2p4r9sd0cib1sp4w9n4yg0gzjahcvs3-libX11-1.6.12-dev/include', '-I/nix/store/4hv04g8figg8gp6aylqp9q64pqy4xsbv-xorgproto-2019.1/include', '-I/nix/store/j3pzr8vam8j46hwlv9f1d6s39hfvsjmc-libXt-1.2.0-dev/include', '-DHAVE_FT=1', '-DHAVE_XMU=1', '-DHAVE_EGL_EGL_H=1', '-DHAVE_GLES3_GL31_H=1', '../src/selmgr.cc', '-c', '-o/build/source/build/src/selmgr.cc.1.o']
[ 6/12] Compiling src/frame.cc
[ 7/12] Compiling src/pty.cc
20:32:44 runner ['g++', '-DZUTTY_VERSION="0.6"', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wsign-compare', '-std=c++14', '-g', '-ggdb', '-O2', '-march=native', '-fno-omit-frame-pointer', '-fPIC', '-fsigned-char', '-Werror', '-I/nix/store/pml24684ad5a8a7n10m8s6xkchncxkyd-freetype-2.10.2-dev/include/freetype2', '-I/nix/store/f95lp0api6ib9bqv7r099mip8ia9gxwv-libXmu-1.1.3-dev/include', '-I/nix/store/s2p4r9sd0cib1sp4w9n4yg0gzjahcvs3-libX11-1.6.12-dev/include', '-I/nix/store/4hv04g8figg8gp6aylqp9q64pqy4xsbv-xorgproto-2019.1/include', '-I/nix/store/j3pzr8vam8j46hwlv9f1d6s39hfvsjmc-libXt-1.2.0-dev/include', '-DHAVE_FT=1', '-DHAVE_XMU=1', '-DHAVE_EGL_EGL_H=1', '-DHAVE_GLES3_GL31_H=1', '../src/frame.cc', '-c', '-o/build/source/build/src/frame.cc.1.o']
20:32:44 runner ['g++', '-DZUTTY_VERSION="0.6"', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wsign-compare', '-std=c++14', '-g', '-ggdb', '-O2', '-march=native', '-fno-omit-frame-pointer', '-fPIC', '-fsigned-char', '-Werror', '-I/nix/store/pml24684ad5a8a7n10m8s6xkchncxkyd-freetype-2.10.2-dev/include/freetype2', '-I/nix/store/f95lp0api6ib9bqv7r099mip8ia9gxwv-libXmu-1.1.3-dev/include', '-I/nix/store/s2p4r9sd0cib1sp4w9n4yg0gzjahcvs3-libX11-1.6.12-dev/include', '-I/nix/store/4hv04g8figg8gp6aylqp9q64pqy4xsbv-xorgproto-2019.1/include', '-I/nix/store/j3pzr8vam8j46hwlv9f1d6s39hfvsjmc-libXt-1.2.0-dev/include', '-DHAVE_FT=1', '-DHAVE_XMU=1', '-DHAVE_EGL_EGL_H=1', '-DHAVE_GLES3_GL31_H=1', '../src/pty.cc', '-c', '-o/build/source/build/src/pty.cc.1.o']
[ 8/12] Compiling src/renderer.cc
20:32:44 runner ['g++', '-DZUTTY_VERSION="0.6"', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wsign-compare', '-std=c++14', '-g', '-ggdb', '-O2', '-march=native', '-fno-omit-frame-pointer', '-fPIC', '-fsigned-char', '-Werror', '-I/nix/store/pml24684ad5a8a7n10m8s6xkchncxkyd-freetype-2.10.2-dev/include/freetype2', '-I/nix/store/f95lp0api6ib9bqv7r099mip8ia9gxwv-libXmu-1.1.3-dev/include', '-I/nix/store/s2p4r9sd0cib1sp4w9n4yg0gzjahcvs3-libX11-1.6.12-dev/include', '-I/nix/store/4hv04g8figg8gp6aylqp9q64pqy4xsbv-xorgproto-2019.1/include', '-I/nix/store/j3pzr8vam8j46hwlv9f1d6s39hfvsjmc-libXt-1.2.0-dev/include', '-DHAVE_FT=1', '-DHAVE_XMU=1', '-DHAVE_EGL_EGL_H=1', '-DHAVE_GLES3_GL31_H=1', '../src/renderer.cc', '-c', '-o/build/source/build/src/renderer.cc.1.o']
[ 9/12] Compiling src/vterm.cc
20:32:44 runner ['g++', '-DZUTTY_VERSION="0.6"', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wsign-compare', '-std=c++14', '-g', '-ggdb', '-O2', '-march=native', '-fno-omit-frame-pointer', '-fPIC', '-fsigned-char', '-Werror', '-I/nix/store/pml24684ad5a8a7n10m8s6xkchncxkyd-freetype-2.10.2-dev/include/freetype2', '-I/nix/store/f95lp0api6ib9bqv7r099mip8ia9gxwv-libXmu-1.1.3-dev/include', '-I/nix/store/s2p4r9sd0cib1sp4w9n4yg0gzjahcvs3-libX11-1.6.12-dev/include', '-I/nix/store/4hv04g8figg8gp6aylqp9q64pqy4xsbv-xorgproto-2019.1/include', '-I/nix/store/j3pzr8vam8j46hwlv9f1d6s39hfvsjmc-libXt-1.2.0-dev/include', '-DHAVE_FT=1', '-DHAVE_XMU=1', '-DHAVE_EGL_EGL_H=1', '-DHAVE_GLES3_GL31_H=1', '../src/vterm.cc', '-c', '-o/build/source/build/src/vterm.cc.1.o']
[10/12] Compiling src/main.cc
20:32:44 runner ['g++', '-DZUTTY_VERSION="0.6"', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wsign-compare', '-std=c++14', '-g', '-ggdb', '-O2', '-march=native', '-fno-omit-frame-pointer', '-fPIC', '-fsigned-char', '-Werror', '-I/nix/store/pml24684ad5a8a7n10m8s6xkchncxkyd-freetype-2.10.2-dev/include/freetype2', '-I/nix/store/f95lp0api6ib9bqv7r099mip8ia9gxwv-libXmu-1.1.3-dev/include', '-I/nix/store/s2p4r9sd0cib1sp4w9n4yg0gzjahcvs3-libX11-1.6.12-dev/include', '-I/nix/store/4hv04g8figg8gp6aylqp9q64pqy4xsbv-xorgproto-2019.1/include', '-I/nix/store/j3pzr8vam8j46hwlv9f1d6s39hfvsjmc-libXt-1.2.0-dev/include', '-DHAVE_FT=1', '-DHAVE_XMU=1', '-DHAVE_EGL_EGL_H=1', '-DHAVE_GLES3_GL31_H=1', '../src/main.cc', '-c', '-o/build/source/build/src/main.cc.1.o']
[11/12] Compiling src/gl.cc
20:32:44 runner ['g++', '-DZUTTY_VERSION="0.6"', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wsign-compare', '-std=c++14', '-g', '-ggdb', '-O2', '-march=native', '-fno-omit-frame-pointer', '-fPIC', '-fsigned-char', '-Werror', '-I/nix/store/pml24684ad5a8a7n10m8s6xkchncxkyd-freetype-2.10.2-dev/include/freetype2', '-I/nix/store/f95lp0api6ib9bqv7r099mip8ia9gxwv-libXmu-1.1.3-dev/include', '-I/nix/store/s2p4r9sd0cib1sp4w9n4yg0gzjahcvs3-libX11-1.6.12-dev/include', '-I/nix/store/4hv04g8figg8gp6aylqp9q64pqy4xsbv-xorgproto-2019.1/include', '-I/nix/store/j3pzr8vam8j46hwlv9f1d6s39hfvsjmc-libXt-1.2.0-dev/include', '-DHAVE_FT=1', '-DHAVE_XMU=1', '-DHAVE_EGL_EGL_H=1', '-DHAVE_GLES3_GL31_H=1', '../src/gl.cc', '-c', '-o/build/source/build/src/gl.cc.1.o']
../src/font.cc: In member function 'void zutty::Font::load()':
../src/font.cc:88:25: error: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Werror=sign-compare]
   88 |          while (nx * ny < n_glyphs)
      |                 ~~~~~~~~^~~~~~~~~~
cc1plus: all warnings being treated as errors

Waf: Leaving directory `/build/source/build'
Build failed
 -> task in 'zutty' failed with exit status 1:
        {task 140737335524688: cxx font.cc -> font.cc.1.o}
['g++', '-DZUTTY_VERSION="0.6"', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wsign-compare', '-std=c++14', '-g', '-ggdb', '-O2', '-march=native', '-fno-omit-frame-pointer', '-fPIC', '-fsigned-char', '-Werror', '-I/nix/store/pml24684ad5a8a7n10m8s6xkchncxkyd-freetype-2.10.2-dev/include/freetype2', '-I/nix/store/f95lp0api6ib9bqv7r099mip8ia9gxwv-libXmu-1.1.3-dev/include', '-I/nix/store/s2p4r9sd0cib1sp4w9n4yg0gzjahcvs3-libX11-1.6.12-dev/include', '-I/nix/store/4hv04g8figg8gp6aylqp9q64pqy4xsbv-xorgproto-2019.1/include', '-I/nix/store/j3pzr8vam8j46hwlv9f1d6s39hfvsjmc-libXt-1.2.0-dev/include', '-DHAVE_FT=1', '-DHAVE_XMU=1', '-DHAVE_EGL_EGL_H=1', '-DHAVE_GLES3_GL31_H=1', '../src/font.cc', '-c', '-o/build/source/build/src/font.cc.1.o']
builder for '/nix/store/1xivays2hrkdrc5sriqj2x4300zqknwp-zutty-c792cf15fba8a6060a85712e5f188cf756d09ad7.drv' failed with exit code 1
error: build of '/nix/store/1xivays2hrkdrc5sriqj2x4300zqknwp-zutty-c792cf15fba8a6060a85712e5f188cf756d09ad7.drv' failed
```

**Comment by jasom** [comment] 2021-01-12 20:40
Persumably something in Nix is adding either `-Wsign-compare` or `-Werror`

**Comment by tomszilagyi** [comment] 2021-01-12 20:46
No, I have those baked in (lines 41 and 43 in `wscript`). The question is why I am not getting the same error with (now) four different versions of GCC, one of them identical to yours? Puzzling...

If I wanted to reproduce the environment you have, would I have to install a full-blown NixOS in a VM or would a setup of Nix be sufficient? (I'm a complete Nix noob, never touched it before.)

**Comment by jasom** [comment] 2021-01-12 21:44
It should also reproduce with nixpkgs installed on whatever distro.  If it doesn't it's probably due to nixpkgs updating a bit more often than NixOS.

[nix install instructions here](https://nixos.org/guides/install-nix.html)

After installing, you can [untar this in your home directory](https://www.dropbox.com/s/vkpmc83ez2w28rz/nixoverlay.tar?dl=0) (it's the overlay I'm using to try zutty on nix) and run `nix-shell '<nixpkgs>' -A zutty` to get the shell environment that it is built in.

If you don't want to go through that hassle, I can run tests for you as well.

**Comment by tomszilagyi** [comment] 2021-01-12 22:04
Awesome, thanks! Will try this soon (hopefully tomorrow).

A tangential comment: the Zutty version in the waf configure output you pasted above is incorrect, it should be something like `0.6-8-gc792cf1` instead of `0.6` (if you are trying the git HEAD). I don't know why, presumably the `git describe ...` command in the `wscript` does not work in the Nix environment and it falls back to the committed content of `version.txt`. Something that might be worth looking into.

**Comment by jasom** [comment] 2021-01-12 22:07
Re: tangential comment

The Nix Github fetch tool downloads tarballs for building rather than doing a git checkout, so `git describe` won't do anything useful.

**Comment by tomszilagyi** [comment] 2021-01-12 22:10
Okay, at least that explains it (:

**Comment by tomszilagyi** [comment] 2021-01-13 20:31
@jasom
I was able to reproduce the problem on an install of Nix (nix-env 2.3.10) over my Debian Testing, using the overlay you provided.
It gives me GCC 10.2.0 (as opposed to 10.2.1 on the machine), so this is certainly not the cause of the error, rather the different flags the compiler itself is built with.
Thanks for all your help diagnosing and helping me reproduce this!

For reference, here's the two compiler signatures:

Nix:
```
y$ g++ -v 
Using built-in specs.
COLLECT_GCC=/nix/store/5wfh94xwg2hd7n82j8klgn4nmf07is24-gcc-10.2.0/bin/g++
COLLECT_LTO_WRAPPER=/nix/store/5wfh94xwg2hd7n82j8klgn4nmf07is24-gcc-10.2.0/libexec/gcc/x86_64-unknown-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: 
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.0 (GCC) 
```

Debian:
```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-3' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-0py4jQ/gcc-10-10.2.1/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-0py4jQ/gcc-10-10.2.1/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20201224 (Debian 10.2.1-3) 
```

**Closed** 2021-01-16 12:31 UTC
