### ISSUE TITLE
Error in the terminal output

### ISSUE THREAD

**Issue by Ved-un** [tomszilagyi/zutty#90] opened 2022-09-12 09:56 UTC
Hello.
Thank you for the program.

Could you please tell me what this error is and whether it affects the startup time?

```
[elem] ~ ❯ time zutty 
E [vterm.icc: 91] Error: Unhandled input char 'q' (113) in state CSI_SPC. Escape sequence so far: '\e[3 q' (5 bytes)
zutty  0,57s user 0,06s system 3% cpu 18,965 total
```

![flameshot_255](https://user-images.githubusercontent.com/48730277/189625792-3629e592-4c31-4589-a076-d95e3b08396a.png)

**Comment by tomszilagyi** [comment] 2022-09-12 13:57
"CSI <n> Space q" is DECSCUSR (set cursor style), a VT520 control sequence not (yet) implemented by Zutty, hence the (harmless) error message.

Duplicate of #85.

**Closed** 2022-09-12 17:27 UTC
