### ISSUE TITLE
Your performance comparison is incorrect

### ISSUE THREAD

**Issue by kovidgoyal** [tomszilagyi/zutty#2] opened 2021-01-12 08:33 UTC
I'm just pointing out here that you turned off scrollback for every terminal (apparently because yours doesnt implement it), except kitty. The relevant setting is ``scrollback_lines`` which defaults to 2000, not ``scrollback_pager_history_size`` which you set to zero for some reason, though it defaults to zero anyway. 

And I'll just point out that how fast a terminal sinks data is a totally meaningless test. It can be trivially gamed in any terminal that uses threaded rendering. You just read data arbitrarily fast on a separate thread, buffer it in memory and process it next year. And claim the prize in any vttest/cat large file benchmark.

**Comment by tomszilagyi** [comment] 2021-01-12 09:10
Hi Kovid,

An honour to have your personal attention here! Let me state up front that I have a lot of respect for your work, even though I disagree with a lot of the opinions you disseminate (but you know that already).

> I'm just pointing out here that you turned off scrollback for every terminal (apparently because yours doesnt implement it), except kitty. The relevant setting is `scrollback_lines` which defaults to 2000, not `scrollback_pager_history_size` which you set to zero for some reason, though it defaults to zero anyway.

You are correct, I made a mistake in my article (corrected), I have in fact set `scrollback_lines` to 0 (I remember fiddling with the config for some time, so that explains it). I now went back and double-checked it. The measurement numbers I am getting are still the same (within fluctuation errors).

As a tangential remark, in case of a reasonable implementation, I don't think the presence of scrollback should influence the numbers achieved on this test at all. In the absence of window resize events, the work of storing data into a circular buffer is the same regardless of how big the circular buffer is. And Zutty will certainly implement scrollback, it is top of the roadmap.

> 
> And I'll just point out that how fast a terminal sinks data is a totally meaningless test. It can be trivially gamed in any terminal that uses threaded rendering. You just read data arbitrarily fast on a separate thread, buffer it in memory and process it next year. And claim the prize in any vttest/cat large file benchmark.

We do not have any disagreement here! By the way, Zutty is not "gaming" it at all, since it is single-threaded (at least the pty reader / vterm parser). It does not buffer and process anything "next year"; all data from the pty is sequentially processed and the current state made visible very shortly after each vsync.

The second performance test in my comparison article is much more meaningful (and Kitty achieves a higher number there).

(closing as it's not a bug, and raised points have been addressed)

**Closed by tomszilagyi** 2021-01-12 09:10 UTC

**Comment by kovidgoyal** [comment] 2021-01-12 09:16
On Tue, Jan 12, 2021 at 01:10:57AM -0800, Tom Szilagyi wrote:
> Hi Kovid,
> 
> An honour to have your personal attention here! Let me state up front that I have a lot of respect for your work, even though I disagree with a lot of the opinions you disseminate (but you know that already).

No worries, and all the best with zutty. I do like the idea of parsing
input on the GPU, although I would be surprised if it is workable once
you get beyond the basic use case of display text. Hyperlinks, for
instance, would be rather difficult to implement. 

> 
> > I'm just pointing out here that you turned off scrollback for every terminal (apparently because yours doesnt implement it), except kitty. The relevant setting is `scrollback_lines` which defaults to 2000, not `scrollback_pager_history_size` which you set to zero for some reason, though it defaults to zero anyway.
> 
> You are correct, I made a mistake in my article (corrected), I have in fact set `scrollback_lines` to 0 (I remember fiddling with the config for some time, so that explains it). I now went back and double-checked it. The measurement numbers I am getting are still the same (within fluctuation errors).
> 
> As a tangential remark, in case of a reasonable implementation, I don't think the presence of scrollback should influence the numbers achieved on this test at all. In the absence of window resize events, the work of storing data into a circular buffer is the same regardless of how big the circular buffer is. And Zutty will certainly implement scrollback, it is top of the roadmap.

Glad to hear it, scrollback is pretty much table stakes :)

**Comment by anarcat** [comment] 2021-01-18 16:04
> Zutty will certainly implement scrollback, it is top of the roadmap.

is there a good way to get notified when that happens? it's pretty much the blocker for adoption for me. should i open an issue?

love your project, congrats on the great performance comparisons, btw. seems to match [my own experiments as well](https://anarc.at/blog/2018-05-04-terminal-emulators-2/#latency) which may mean something, or not. ;)

**Comment by tomszilagyi** [comment] 2021-01-18 17:15
Thanks for your interest in Zutty, I am aware and have read your comparisons as prior art to my articles :)

You don't have to open an issue. If I land scrollback support in Zutty I will make a new release (https://github.com/tomszilagyi/zutty/releases), not sure if GitHub allows you to sign up for an RSS of releases. But I will surely post an article on my blog as well, and for that you *can* subscribe to an RSS (https://tomscii.sig7.se/feed.xml).

Sorry for not having better project infrastructure, Zutty is a little hobby project of mine (seems to have gotten quite some attention lately, which is not bad, but I have very limited resources to spend on admin stuff).

**Comment by anarcat** [comment] 2021-01-18 18:38
> Thanks for your interest in Zutty, I am aware and have read your comparisons as prior art to my articles :)

That's great to hear, thanks! :) Glad that might have been useful...

> If I land scrollback support in Zutty I will make a new release (https://github.com/tomszilagyi/zutty/releases), not sure if GitHub allows you to sign up for an RSS of releases.

That's fine. And yes, there are RSS feeds:

- https://github.com/tomszilagyi/zutty/tags.atom
- https://github.com/tomszilagyi/zutty/releases.atom
- https://github.com/tomszilagyi/zutty/commits/master.atom

I'll subscribe to one of those, thanks!

> Sorry for not having better project infrastructure, Zutty is a little hobby project of mine (seems to have gotten quite some attention lately, which is not bad, but I have very limited resources to spend on admin stuff).

Hey don't apologize, this is all fine. We got everything we need here, just focus on the good code and being as nice to people as you already are. :)

**Comment by kovidgoyal** [comment] 2021-01-23 06:50
I see you have latency comparisons too now, that is good, latency is by far more important than throughput. And just so you know, kitty deliberately introduces input latency, details here: https://sw.kovidgoyal.net/kitty/performance.html

Since kitty and xterm are the best latency terminal emulators you compare with, you should set the input_delay in kitty.conf to zero for an apples-to-apples comparison of raw latency. And note that if you are serious about creating an actually useable terminal emulator, you will need something like input_delay yourself, otherwise you will get flickering in full screen programs that dont support the atomic screen update escape code, the george and egmont and I created.

**Comment by anarcat** [comment] 2021-03-01 00:59
> If I land scrollback support in Zutty I will make a new release (https://github.com/tomszilagyi/zutty/releases), not sure if GitHub allows you to sign up for an RSS of releases.

Just to wrap-up this one... I did notice the 0.8 release, and it seems it ships with scrollback support, but I noticed only because I went through the commit list.. It would be nice to include a human-readable changelog (especially since GitHub doesn't show tags in the commit list by default, so it's hard to tell when to stop reading... ;)

Thanks again!

**Comment by tomszilagyi** [comment] 2021-03-01 10:48
Yes, the main feature of 0.8 is scrollback support (along with several other improvements).
Thanks for sharing your observation regarding the (lack of) ChangeLog, will see what I can do about it.
The unspoken assumption here was that so few people are already interested in Zutty that its history is not too important -- all users are new users...

**Comment by anarcat** [comment] 2021-03-01 14:59
i guess that's true: i'm still a "new user", as I haven't switched yet. but i read the README already, and it's somewhat inconvenient to diff it.

re changelog: nothing fancy is needed, just a few bullet points in the git tag does wonders already, as it shows up in the "release" when you pick the tag from the drop down. for some reason i cannot fathom though, it doesn't properly format markdown nor reuse the first line as a title, which you'd think would be fairly obvious...

anyways, sorry for hijacking this thread any further, i'll let you go back to real work now. thanks again! :)

**Comment by tomszilagyi** [comment] 2021-03-01 15:34
No worries at all, thanks for bringing it up!
I think you got what you wanted, check here: https://github.com/tomszilagyi/zutty/releases
It was a simple matter of pasting the output of `git log 0.7..0.8 --reverse --pretty="- %s (%h)"` into the tag editor, so not a big deal.

**Comment by anarcat** [comment] 2021-03-01 15:40
i actually use a curated version of the output of `git-changelog` from [git-extras](https://github.com/tj/git-extras) FWIW. :)
