### ISSUE TITLE
Ctrl-/ in vim

### ISSUE THREAD

**Issue by nadevko** [tomszilagyi/zutty#76] opened 2022-05-22 15:59 UTC
In neovim, <kbd>Ctrl-[</kbd> and <kbd>Ctrl-]</kbd> returns <kbd>\<C-3></kbd> and <kbd>\<C-5></kbd> unstead of <kbd>^[</kbd> and <kbd>^]</kbd>.

**Comment by tomszilagyi** [comment] 2022-05-22 17:29
Did it work before the fix for #61 was merged? 
I tried nvim in xterm and (latest) zutty side-by-side, same keys, same results.
You either need to give me a *much* more complete report, or debug it yourself.

**Comment by tomszilagyi** [comment] 2022-05-23 19:17
Cannot reproduce this. There is literally no difference (that I can sense) in how zutty and xterm behaves when this key is pressed.
Ctrl-/ echoes as `^_` in zutty, just as in xterm. nvim looks and behaves the same.

I encourage you to study the keyboard handling specs of [zutty](https://tomscii.sig7.se/zutty/doc/KEYS.html) as well as [xterm](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Special-Keyboard-Keys), study the behaviour of these programs with whatever settings are important to you, and come back with a more thorough description of what you actually see, what you would like to see instead, and why.

**Comment by tomszilagyi** [comment] 2022-05-24 21:23
ok, got it now. Will fix.

**Closed** 2022-05-28 12:28 UTC
