### ISSUE TITLE
Zutty adding '-' to beginning of file in vim

### ISSUE THREAD

**Issue by paulie-g** [tomszilagyi/zutty#20] opened 2021-03-12 09:13 UTC
Every file I open in vim somehow ends up with a '-' prepended to it. This is not just a display artefact, it is really there in the buffer, but vim remains in normal mode. Log:

```
E [vterm.icc: 94] Error: Unhandled input char 'm' (109) in state 13. Escape sequence so far: '\e[>4;2m' (7 bytes)
W [vterm.icc:1491] (Unimplemented) Start blinking cursor
W [vterm.icc:1540] (Unimplemented) Stop blinking cursor
W [vterm.icc:1713] (Unimplemented) attribute: 29
W [vterm.icc:1821] (Unimplemented) DCS: 'zz'
E [vterm.icc: 94] Error: Unhandled input char '%' (37) in state 7. Escape sequence so far: '\e[0%' (4 bytes)
W [main.cc:897] (Unimplemented) unhandled OSC: '10;?'
W [main.cc:897] (Unimplemented) unhandled OSC: '11;?'
W [main.cc:897] (Unimplemented) unhandled OSC: '12;%p1%s'
W [main.cc:897] (Unimplemented) unhandled OSC: '12;%p1%s'`
```

**Comment by paulie-g** [comment] 2021-03-13 08:19
Ok, did a bit of digging and the problem is essentially that zutty advertises itself as xterm-256color, but does not implement all the capabilities advertised in its terminfo. Specifically, vim > 8.1.something outputs special escape codes that rely on xterm's modifyOtherKeys functionality, which appears not to be implemented in zutty.

See: https://vi.stackexchange.com/questions/27399/whats-t-te-and-t-ti-added-by-vim-8

Unfortunately, the simple workaround listed there that can be applied to vimrc doesn't quite work.

**Comment by tomszilagyi** [comment] 2021-03-13 09:13
The garbage character being inserted ('-' for you, different for me) is due to an unrelated control flow error in Zutty (it answers to an unimplemented DCS sequence that it should not, in a way that ends up what vim thinks is input). I will push a fix that should close this issue.

Regarding the `modifyOtherKeys` feature of Xterm (https://invisible-island.net/xterm/modified-keys.html) which is enabled by `\e[4;2m`: that is something I might implement later, but it is a little bit more involved. In the meantime you might want to implement the workaround in the linked SE article to stop Vim from using this capability. Unless you do rely on the keyboard mappings made possible by that, in which case you are better off using another terminal (at least for now).

As a side note: I have not been able to dig up any spec for what `\e[0%m` is for, and it seems that xterm does not interpret it either. Same for the DCS 'zz' (`\ePzz\e\\`). Let me know if you have any idea what those are for. My usual go-to reference is https://invisible-island.net/xterm/ctlseqs/ctlseqs.html -- if it's not specified there, I have a hard time implementing support for it.

**Comment by paulie-g** [comment] 2021-03-13 09:59
This explains why even unsetting t_TI and t_TE still left me with a blank line being prepended, I'm assuming. I zeroed in on this explanation since it was visible in the logs. I can do without that feature for now, and still use kitty as my default for now (although I do enjoy zutty's responsiveness, just came across this issue and haven't tested all my use cases yet).

No idea, best guess for [0%m is SGR of some kind, but no idea really. Frankly, I've long resolved that in that there forest goblins live and generally try to avoid learning more than I need to fix things lest it displaces something useful in my memory banks.

The best way forward would, I suspect, be for me to wait for your push, test again and see what issues remain. The other issues might go away, or they might be something to do with powerline and not important (to me).

**Comment by tomszilagyi** [comment] 2021-03-13 17:13
Please do so, it is interesting feedback for me so please do report any remaining incompatibilities.

**Closed** 2021-03-13 20:56 UTC

**Comment by subnut** [comment] 2021-03-15 14:48
Well, @tomszilagyi I am seeing a similar behaviour.
Running on commit `1c0f99b`, I observe that, upon starting vim, the contents of the `"-` register are automatically present in the buffer!
Most probably the terminal is doing something that vim seems to interpret as the keypresses `"` `-` `p`

Can you reproduce it?

**Comment by subnut** [comment] 2021-03-15 14:50
Also, I see that the problem I reported above does not occur in nvim.
I don't know why.

**Comment by tomszilagyi** [comment] 2021-03-15 15:20
> Well, @tomszilagyi I am seeing a similar behaviour.
> Running on commit `1c0f99b`, I observe that, upon starting vim, the contents of the `"-` register are automatically present in the buffer!
> Most probably the terminal is doing something that vim seems to interpret as the keypresses `"` `-` `p`
> 
> Can you reproduce it?

Can you please test with the latest master (eaa36ca)?

**Comment by subnut** [comment] 2021-03-15 15:31
Okay, I tested with latest master, the problem seems to be gone.
Thanks :+1:

**Comment by alanswanson** [comment] 2022-02-11 15:26
As a reference, with vim the unimplemented `DCS: 'zz' `and escape sequence `'\e[0%'` are part of a test for getting cursor style from https://github.com/vim/vim/commit/a45551a53557dba98973fdb3ff737dea2fffcda3 see check_terminal_behavior() in src/term.c.
