### ISSUE TITLE
No suitable files for '9x18' found!

### ISSUE THREAD

**Issue by kseistrup** [tomszilagyi/zutty#26] opened 2021-04-01 09:21 UTC
I compiled the latest release and the latest git commit without problems on ArchLinux¹. However, both of them aborts with this error message:

```sh
$ zutty
terminate called after throwing an instance of 'std::runtime_error'
  what():  No suitable files for '9x18' found!
Job 1, 'zutty' terminated by signal SIGABRT (Abort)
```

I assume it is a font issue. I'm not aware how to solve the problem, though. Installing a 9×18 font didn't seem to work.

Any suggestions?

----

1. https://aur.archlinux.org/packages/zutty/ & https://aur.archlinux.org/packages/zutty-git/

**Comment by tomszilagyi** [comment] 2021-04-01 10:51
Hi!

Thanks for the report, I do not use Arch so my first suggestion is that you file an issue against the Arch package.
Presumably, the default font of Zutty is not installed on Arch as a dependency of Zutty.

You can find more info about the font handling of Zutty here:
https://tomscii.sig7.se/zutty/doc/USAGE.html#Font%20selection
This goes into details about how fonts are found by Zutty and what you might want to do to make it succeed.

The misc-fixed fonts (which contain 9x18) are usually packaged as something called `xbase-fonts` or similar. But I'm surprised they are not already present on any Linux desktop (I would certainly consider such a situation a regression, and complain to the maintainers of said distro).

If all else fails, you can manually get the misc-fixed fonts (including 9x18) from here:
https://tomscii.sig7.se/zutty/doc/USAGE.html#Font%20selection

**Comment by tomszilagyi** [comment] 2021-04-01 10:56
Okay, so I forgot the part where you said "installing the 9x18 font did not seem to work".
I think you should run Zutty with the `-v` option (from another terminal), and look at its output.
There you will see the path where it is looking for fonts. Try to reconcile that with where your fonts really are, and if necessary, pass the `-fontpath` option to Zutty. If that works, you can set up a resource setting for it (to override the default path), look at the Zutty docs for how to do that.
If you get stuck, feel free to come back with details and I will try to help.

**Comment by kseistrup** [comment] 2021-04-07 09:32
Thank you.

Explicitly stating the font name did help, e.g. `zutty -font 'Hack'`, although it didn't work for the font that I currently use in my terminal emulator, “JetBrains Mono Medium” (I think I tried all combinations of these words, with and without spaces), which may be why zutty failed in the first place.

I have to admit that I know next to nothing about how fonts work, they usually just do. Thankfully we don't have to use the cryptic font specifications we used with X two decades years ago.

**Comment by tomszilagyi** [comment] 2021-04-07 10:12
There is no cleverness involved. Zutty has to be able to find a font file under its set of font search paths (`-fontpath`) that contains the fontname *exactly*. Yes, you need to quote spaces and other shell-special chars.

If you want to see what files Zutty will consider for a given `-font '<something>'`, do something like this:
`find /usr/share/fonts -name <something>\*`

This will list all files with names that start with `<something>` under `/usr/share/fonts`.
That is assuming that you have not altered the fontpath (`/usr/share/fonts` is the default).

For example, I get:

```
$ find /usr/share/fonts -name 9x18\*
/usr/share/fonts/X11/misc/9x18-KOI8-R.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-3.pcf.gz
/usr/share/fonts/X11/misc/9x18.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-13.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-4.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-16.pcf.gz
/usr/share/fonts/X11/misc/9x18B-ISO8859-5.pcf.gz
/usr/share/fonts/X11/misc/9x18B-ISO8859-8.pcf.gz
/usr/share/fonts/X11/misc/9x18B-ISO8859-4.pcf.gz
/usr/share/fonts/X11/misc/9x18B-ISO8859-13.pcf.gz
/usr/share/fonts/X11/misc/9x18B-ISO8859-7.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-14.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-9.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-10.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-15.pcf.gz
/usr/share/fonts/X11/misc/9x18B-ISO8859-10.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-2.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-5.pcf.gz
/usr/share/fonts/X11/misc/9x18B-ISO8859-9.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-1.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-8.pcf.gz
/usr/share/fonts/X11/misc/9x18B-ISO8859-3.pcf.gz
/usr/share/fonts/X11/misc/9x18B.pcf.gz
/usr/share/fonts/X11/misc/9x18B-ISO8859-1.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-11.pcf.gz
/usr/share/fonts/X11/misc/9x18-ISO8859-7.pcf.gz
/usr/share/fonts/X11/misc/9x18B-ISO8859-2.pcf.gz
/usr/share/fonts/X11/misc/9x18B-ISO8859-14.pcf.gz
/usr/share/fonts/X11/misc/9x18B-ISO8859-16.pcf.gz
/usr/share/fonts/X11/misc/9x18B-ISO8859-15.pcf.gz
```

Of those files, Zutty will pick what it thinks is best, evidenced by its verbose output:

```
$ zutty -v
...
I [font.cc: 54] Loading /usr/share/fonts/X11/misc/9x18.pcf.gz as primary
I [font.cc:198] Glyph size 9x18
I [font.cc: 54] Loading /usr/share/fonts/X11/misc/9x18B.pcf.gz as overlay
I [font.cc:198] Glyph size 9x18
```

Hope this helps with debugging (if you want to try more fonts).

**Comment by tomszilagyi** [comment] 2021-04-07 10:14
Closing issue because there is no issue with Zutty.

**Closed by tomszilagyi** 2021-04-07 10:14 UTC

**Comment by kseistrup** [comment] 2021-04-07 10:35
Thanks, you're right. Using

```
$ zutty -v -font 'JetBrainsMono-Medium' -fontpath /usr/share/fonts/TTF
```

does work. It's slightly inconvenient because I have to know the actual name of the font file — _and_ the path. My current terminal emulator, `sakura`, lists the font as “JetBrains Mono Medium” and finds it without an excplicit path. In fact, all other terminal emulators I have tried have no problems in this regard, so `zutty` behave unexpectedly to me (although not necessarily wrong, now that I know the solution).

**Comment by tomszilagyi** [comment] 2021-04-07 11:08
You can set up defaults for those in your `~/.Xresources` so you don't have to type those arguments every time (see https://tomscii.sig7.se/zutty/doc/USAGE.html#Persistent%20configuration for details).
Then you can pretty much forget about this.

**Comment by tomszilagyi** [comment] 2021-04-07 11:11
And just a note, you should not have to supply `-fontpath` in your above example, because Zutty does a recursive (depth) search, and your path is within (below) the default `/usr/share/fonts`, so you should be able to omit it. Zutty does *not* require that you specify the explicit path, only a search path where it can be found. And system-wide installed fonts will be there under the default (unless you use a funky system like NixOS where this is not true).

**Comment by kseistrup** [comment] 2021-04-07 11:17
Thanks!

**Comment by pveentjer** [comment] 2021-06-06 14:51
Is there a reason why only pcf.gz files are picked up?

```
      if (strcasecmp (ext, ".ttf") != 0 &&
          strcasecmp (ext, ".otf") != 0 &&
          strcasecmp (ext, ".pcf.gz") != 0)
         return 0;
```

**Comment by pveentjer** [comment] 2021-06-06 17:47
I'll make a PR.

**Comment by tomszilagyi** [comment] 2021-06-06 20:53
> Is there a reason why pcf.gz files are picked up but .pcf (no gz) are not?

Thanks for asking!
Not really, other than the fact that the systems I tested Zutty on have only contained compressed pcf files.
But I am happy to add the ".pcf" extension if it turns out to be useful.
N.B., there are many more extensions recognized by freetype but not allowed by the simple extension filter you quoted (rough heuristic on my part to get there 90% of the way), so the list of accepted file types is bound to grow. It just needs some careful testing and showcasing a few good fonts that are enabled by each addition.
